### ISSUE TITLE
How to make obj file in custom datasets?

### ISSUE THREAD

**Issue by iamblitzcrank** [THU-luvision/XScale-NVS#1]
Hello, I'm trying to process this code, however, I cannot make obj file of my custom datasets.
I'm using Tanks&Temples, NeRF-synthetic, mipnerf360 dataset, but there is no obj file.
Could you explain more details how to make obj file?

**Comment by ansj11** [comment]
I am using colmap dataset, but also got an error "ValueError: string is not a file: data/2802/1.obj". Do you have solved the problem?

**Comment by luciancosw** [comment]
Hi @iamblitzcrank @ansj11 ,

Sorry for the confusion. The input mesh can be any format supported by trimesh, including `.obj`, `.ply`, etc. We have added a corresponding config modification in the latest commit.

For example, the default mesh reconstruction from colmap is `meshed-poisson.ply`. In this case, please set the `meshName` (L105 in config/parameter.py) as `meshed-poisson.ply` and this will probably work.

**Comment by luciancosw** [comment]
> Hello, I'm trying to process this code, however, I cannot make obj file of my custom datasets. I'm using Tanks&Temples, NeRF-synthetic, mipnerf360 dataset, but there is no obj file. Could you explain more details how to make obj file?

These datasets may only contain multi-view images (and colmap sparse reconstruction). We need to perform dense multi-view stereo and mesh reconstruction to get the mesh for each scene, for which _agisoft metashape_ or _COLMAP_ are strongly recommoned. For more details, please refer to the _Multi-view 3D reconstruction (A.K.A. Photogrammetry)_ session in the README.

**Comment by yh-yoon** [comment]
Thanks for your response!

**Comment by iamblitzcrank** [comment]
I'll check about it. Thanks!
