### ISSUE TITLE
pytorch3d installation issues

### ISSUE THREAD

**Issue by hajoxs** [THU-luvision/XScale-NVS#12]
Your work is very good, I have an environment installation problem to ask you, I installed pytorch3d, but in the base_utils.py file in the utils file it shows that it can't parse the import of “pytorch3d.transforms, and in the ply.py file it shows that it can't parse the import of “pytorch3d.structures”.

**Comment by luciancosw** [comment]
Hi @hajoxs,
Thanks for your interest in our work and for reporting this issue! Indeed the current release **does not** rely on `pytorch3d`, and the `create_novel_view` method that uses `pytorch3d` in `dataset/data.py` can be deprecated now. You can simply pull the latest release and the issue will not exist anymore:)

**Comment by hajoxs** [comment]
Thanks
