### ISSUE TITLE
tinycudann and nvdiffrast installation issues

### ISSUE THREAD

**Issue by hajoxs** [THU-luvision/XScale-NVS#13]
Thanks for your excellent work, when I try to install both tinycudann and nvdiffrast python libraries at the same time, it seems that both libraries can't exist at the same time!

**Comment by luciancosw** [comment]
Hi @hajoxs, 

Thanks for appreciating our work. 
It is strongly recommended to install `tinycudann` and `nvdiffrast` through `pip`, using the following commands:
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
`pip install git+https://github.com/NVlabs/nvdiffrast/`
Let me know if you still have problems after the re-installation:)

**Comment by hajoxs** [comment]
Thank you for your reply, I noticed that your work was done on Ubuntu OS, I would like to run this code on Windows, I wonder if this is the reason why it is not possible to install both tinycudann and nvdiffrast at the same time!

**Comment by hajoxs** [comment]
By the way, when will the GigaMVS dataset be shared, I noticed the GigaMVS Challenge, but it's now over and I can't download the data, thanks!

**Comment by luciancosw** [comment]
> Thank you for your reply, I noticed that your work was done on Ubuntu OS, I would like to run this code on Windows, I wonder if this is the reason why it is not possible to install both tinycudann and nvdiffrast at the same time!

Sorry to tell that we have currently tested the code only on Ubuntu OS. However, I do not think this is the main reason for inconsistencies between these pakedges. Maybe you can try to build from source according to their official guidance ([tinycudann](https://github.com/NVlabs/tiny-cuda-nn) and [nvdiffrast](https://nvlabs.github.io/nvdiffrast/#installation)), where both of them do have supports for Windows.

**Comment by luciancosw** [comment]
> By the way, when will the GigaMVS dataset be shared, I noticed the GigaMVS Challenge, but it's now over and I can't download the data, thanks!

Thanks again for your interests in our work. I will contact our website managers to open the download link again as soon as possible.

**Comment by hajoxs** [comment]
> > Thank you for your reply, I noticed that your work was done on Ubuntu OS, I would like to run this code on Windows, I wonder if this is the reason why it is not possible to install both tinycudann and nvdiffrast at the same time!
> 
> Sorry to tell that we have currently tested the code only on Ubuntu OS. However, I do not think this is the main reason for inconsistencies between these pakedges. Maybe you can try to build from source according to their official guidance ([tinycudann](https://github.com/NVlabs/tiny-cuda-nn) and [nvdiffrast](https://nvlabs.github.io/nvdiffrast/#installation)), where both of them do have supports for Windows.

Thanks for your reply, I will go to the official tinycudann and nvdiffrast for help and try again on windows!

**Comment by hajoxs** [comment]
> > By the way, when will the GigaMVS dataset be shared, I noticed the GigaMVS Challenge, but it's now over and I can't download the data, thanks!
> 
> Thanks again for your interests in our work. I will contact our website managers to open the download link again as soon as possible.

Thanks!
