### ISSUE TITLE
about .obj file

### ISSUE THREAD

**Issue by luoww1992** [THU-luvision/XScale-NVS#2]
this is no  obj file with colmap after Multi-view 3D reconstruction ！

**Comment by luciancosw** [comment]
Hi @luoww1992,

Sorry for the confusion. Actually the input mesh can be any format supported by trimesh, including `.obj`, `.ply`, etc. We have added a corresponding config modification in the latest commit.

The default mesh reconstruction from colmap is `meshed-poisson.ply`. In this case, please set the `meshName` (L105 in `config/parameter.py`) as  `meshed-poisson.ply` and this will probably work.

**Comment by luoww1992** [comment]
@GuangyuWang99 
i have try to except meshed-poisson.ply to 1.obj by meshlab,
but when i run cmd:
python colmap2mvsnet.py --dense_folder data/boli/dense/0
it show me error:
AttributeError: Can't get attribute 'calc_score' on <module '__mp_main__',  but the func is in file !

after colmap, the data fold likes:
![image](https://github.com/THU-luvision/XScale-NVS/assets/45957595/b507b9f4-58e1-4935-a4aa-b0eacc9ba793)
my dense_folder is data/boli/dense/0, is right ? or the right path is data/boli/sparse/0

**Comment by luoww1992** [comment]
@GuangyuWang99 
my colmap cmd:
colmap automatic_reconstructor --workspace_path $DATASET_PATH --image_path $DATASET_PATH/images --use_gpu 1 --gpu_index 0
