### ISSUE TITLE
some error in pre and train

### ISSUE THREAD

**Issue by luoww1992** [THU-luvision/XScale-NVS#3]
1, error when run:  
    bash graphs/warping/warp.sh
    i have installed all packages, i see the sh file to look how to run code,  when run code about giga_warping.py,
show error: 
DLL load failed while importing nvdiffrast_plugin: 找不到指定的模块.

**Comment by luciancosw** [comment]
> 1, error when run: bash graphs/warping/warp.sh i have installed all packages, i see the sh file to look how to run code, when run code about giga_warping.py, show error: DLL load failed while importing nvdiffrast_plugin: 找不到指定的模块.

I think this is indeed an installation issue regarding nvdiffrast. Please refer to the official repo. for solutions, e.g., you may have a look into this [issue](https://github.com/NVlabs/nvdiffrast/issues/46).
