### ISSUE TITLE
nvdiffrast_plugin

### ISSUE THREAD

**Issue by luoww1992** [THU-luvision/XScale-NVS#5]
i have installed nvdiffrast==0.3.1,
while runing error:
ImportError: DLL load failed while importing nvdiffrast_plugin: 找不到指定的模块

i use glctx = dr.RasterizeCudaContext() instead of dr.RasterizeGLContext()
my env is:
 win10 +py3.9+torch1.13+cuda11.7+cudnn8.5+ A6000

**Comment by luciancosw** [comment]
> i have installed nvdiffrast==0.3.1, while runing error: ImportError: DLL load failed while importing nvdiffrast_plugin: 找不到指定的模块
> 
> i use glctx = dr.RasterizeCudaContext() instead of dr.RasterizeGLContext() my env is: win10 +py3.9+torch1.13+cuda11.7+cudnn8.5+ A6000

I think this is an issue related to [nvdiffrast](https://github.com/NVlabs/nvdiffrast), please refer to the original repository for installation guidance.
