### ISSUE TITLE
安装虚拟环境

### ISSUE THREAD

**Issue by lijinchang-shazhu** [THU-luvision/XScale-NVS#6]
CondaValueError: could not parse 'name: xscalenvs' in: environment.yml

**Comment by luciancosw** [comment]
Hi @lijinchang-shazhu,

Sorry for the confusion. You can install the dependencies by running: `conda env create -f environment.yml`. Btw, it is strongly recommended to manually install the dependencies listed in `environment.yml` one by one.

**Comment by lijinchang-shazhu** [comment]
Thank you very much for your reply and help！
